name: Build and Deploy
on:
  push:
    branches: [main]  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install  # Replace with your build command
      - name: Build
        run: npm run build  # Replace with your build command
      - name: Copy public folder to root
        run: cp -r public/. .
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .  # The root directory containing your built files